const fs = require('fs');

const configContent = `// Supabase Configuration (Generated by Vercel Build)
// =====================================

const SUPABASE_URL = '${process.env.SUPABASE_URL}';
const SUPABASE_ANON_KEY = '${process.env.SUPABASE_ANON_KEY}';

// Initialize Supabase client
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Export for use in other modules
window.supabaseClient = supabase;
`;

// Only create the file if environment variables are present (Production/Vercel)
if (process.env.SUPABASE_URL) {
    fs.writeFileSync('js/supabase-config.js', configContent);
    console.log('✅ js/supabase-config.js created successfully from environment variables.');
} else {
    console.log('⚠️ No environment variables found. Skipping js/supabase-config.js creation (using local file if exists).');
}
